ad:
  map:
    enable: false
  oin:
    enable: true
    tooltip: preview the ad
    path:
      template: \${0}
      fields:
        - src
  chart:
    enable: false
background:
  map:
    enable: false
  oin:
    enable: true
    tooltip: preview the reality
    path: 
      template: http://localhost:3001/b/\${0}
      fields:
        - _id
  chart:
    enable: false