const constants = {
  SET_DEFINITIONS: "SET_DEFINITIONS",
  SET_PROPERTIES: "SET_PROPERTIES",
  SET_USER: "SET_USER",
  SELECT_DEFINITION: "SELECT_DEFINITION",
  SET_UICONFIG: "SET_UICONFIG",
  SET_DEFINITION_QUERY: "SET_DEFINITION_QUERY",
  SET_SNACKER: "SET_SNACKER"
}

export default constants
