analysis:
  map:
    enable: false
  oin:
    enable: false
  chart:
    enable: false
eye:
  map:
    enable: true
    lat: source.geo.lat
    lon: source.geo.lon
  oin:
    enable: true
    tooltip: enter the eye
    path: 
      template: http://localhost:8888/v1/eye/$\${0}?cts=\${1}
      fields:
        - _id
        - _sys.created_ts
  chart:
    enable: true
    xAxis: name
    yAxis:
      - field: source.geo.lat
        name: Lat
        serie: line
        type: value
        area: {}
      - field: _sys.created_by
        name: CB
        serie: bar
        type: category
      - field: _sys.created_ts
        name: Time
        serie: bar
        type: time